### PR TITLE
Alex Coudray - Kerian Thuillier - Milestone 3

### PR DESCRIPTION
**Pull request by kthuillier**
Add our milestone 3 in zip format (unable to refract (sub-)package name to prevent error)

### CODE REVIEW

**Comment by kthuillier** [comment]
Resolve a .gitignore conflict (which occur for an unknown reason).

**Comment by kthuillier** [comment]
MileStone 5 - Kerian Thuillier and Alex Coudray
Everything work correctly: multi-solvers with multi-expression / multi-filename

**Comment by kthuillier** [comment]
Milestone 6 - Final pull request
It contains our report, our code and our data.

**Comment by FAMILIAR-project** [comment]
Excellent work, congratulations and thanks! The report is really interesting as well as the overall code. I cannot accept the PR due to multiple conflicts with files (mostly xtendbin). Can you slightly modify your PR to avoid such conflicts? Otherwise I will try to find a solution

**Comment by kthuillier** [comment]
Good evening Sir,
I will do my best to solve this issue for tomorrow.

**Comment by kthuillier** [comment]
Good morning, 
I am sorry, I could not solve this PR issue : I replace all the problematic files with their associated version in the main depository without solving the issue. I do not know what can solve it.

Do you have any suggestion for me ?

Have a nice day,
Kerian

**Pull request closed without merging**
